SELECT XMLAgg(XMLElement(EVALNAME TM.XMLIDENTIFIER
       ,XMLAttributes
       (
             WFN.PROCESSNAME||'_'||WFN.NODETYPE||'_'||WFN.NODEID AS "id"
             ,WFN.TITLE AS "name"
       )
       ,
       (
             SELECT XMLAgg(XMLElement("bpmn:incoming",TM.NODETYPE||'_'||WFA_OUTCOME.ACTIONID) ORDER BY WFN.NODEID)
             FROM WFACTION WFA_OUTCOME
             ,TYPE_MAPPING TM
             WHERE 1=1
             AND WFN.NODEID=WFA_OUTCOME.MEMBERNODEID(+)
             AND WFN.PROCESSNAME=WFA_OUTCOME.PROCESSNAME(+)
             AND WFN.PROCESSREV=WFA_OUTCOME.PROCESSREV(+)
             AND TM.NODETYPE='ACTION'
       )
       ,
       (
             SELECT XMLAgg(XMLElement("bpmn:outgoing",TM.NODETYPE||'_'||WFA_INCOME.ACTIONID) ORDER BY WFN.NODEID)
             FROM WFACTION WFA_INCOME
             ,TYPE_MAPPING TM
             WHERE 1=1
             AND WFN.NODEID=WFA_INCOME.OWNERNODEID(+)
             AND WFN.PROCESSNAME=WFA_INCOME.PROCESSNAME(+)
             AND WFN.PROCESSREV=WFA_INCOME.PROCESSREV(+)
             AND TM.NODETYPE='ACTION'
       )
 ))
 FROM WFNODE WFN
 ,TYPE_MAPPING TM
 WHERE 1=1
 AND WFN.PROCESSNAME=WFP.PROCESSNAME
 AND WFN.PROCESSREV=WFP.PROCESSREV
 AND WFN.NODETYPE=TM.NODETYPE(+) 
Here is another sample code which converts Maximo Workflow (very basic) coordinates into BPMN Edges:

 SELECT XMLAgg(XMLElement("bpmndi:BPMNEdge"
       ,XMLAttributes
       (
             WFA.WFACTIONID AS "id"
             ,WFA.ACTIONID AS "bpmnElement"
       )
       ,XMLElement
       ("di:waypoint"
             ,XMLAttributes
             (
				 (WFN_OWNER.XCOORDINATE*WFP.X_MULTIPLIER)+TM_OWNER.WIDTH AS "x"
				 ,WFN_OWNER.YCOORDINATE*WFP.X_MULTIPLIER+(TM_OWNER.HEIGHT/2)+TM_OWNER.YDISPLACEMENT AS "y"
             )
       )
       ,XMLElement("di:waypoint"
             ,XMLAttributes
             (
				 (WFN_MEMBER.XCOORDINATE*WFP.X_MULTIPLIER)+TM_MEMBER.XSHIFT AS "x"
				 ,WFN_MEMBER.YCOORDINATE*WFP.X_MULTIPLIER+(TM_MEMBER.HEIGHT/2)+TM_MEMBER.YDISPLACEMENT AS "y"
             )
       )
 ))
 FROM WFACTION WFA
 ,WFNODE WFN_OWNER
 ,WFNODE WFN_MEMBER
 ,TYPE_MAPPING TM_OWNER
 ,TYPE_MAPPING TM_MEMBER
 WHERE 1=1
 AND WFA.OWNERNODEID=WFN_OWNER.NODEID
 AND WFA.PROCESSNAME=WFN_OWNER.PROCESSNAME
 AND WFA.PROCESSREV=WFN_OWNER.PROCESSREV
 AND WFA.MEMBERNODEID=WFN_MEMBER.NODEID
 AND WFA.PROCESSNAME=WFN_MEMBER.PROCESSNAME
 AND WFA.PROCESSREV=WFN_MEMBER.PROCESSREV
 AND WFA.PROCESSNAME=WFP.PROCESSNAME  
 AND WFA.PROCESSREV=WFP.PROCESSREV
 AND WFN_OWNER.NODETYPE=TM_OWNER.NODETYPE(+)
 AND WFN_MEMBER.NODETYPE=TM_MEMBER.NODETYPE(+) 
